### ISSUE TITLE
ee4 rest api - get registration details based on reg_id using oauth authentication

### ISSUE THREAD

**Issue by msyadav88** [eventespresso/eea-rest-api#39] opened 2015-09-24 17:50 UTC
I have setup the wp auth server and get all registrations on executing http://v2.iregister.ie/wp-json/ee/v4.6/registrations
But If I want to get registration details with reg_id = 94 
http://v2.iregister.ie/wp-json/ee/v4.6/registrations?filter[where][REG_ID]=94
Then its giving the below error
Array(
    [result] => Array (
            [0] => Array (
                    [code] => json_registrations_cannot_list
                    [message] => Sorry, you are not allowed to list registrations. Missing permissions: ee_read_registrations,ee_read_others_registrations
                )
   )
   [code] => 403
    [content_type] => application/json; charset=UTF-8
)

PLease guide me to overcome this issue.

**Comment by mnelson4** [comment] 2015-09-24 18:14
hi @msyadav88, so you're saying that accessing `http://v2.iregister.ie/wp-json/ee/v4.6/registrations` works fine (no error), and lists all the registrations (including the one with REG_ID=94), but as soon as you add `?filter[where][REG_ID]=94` onto the end you get the error?

**Comment by msyadav88** [comment] 2015-09-24 18:22
Yes, absolutely right, And also http://v2.iregister.ie/wp-json/ee/v4.6/registrations/94 is working properly and displaying registration detail with id=94

**Comment by mnelson4** [comment] 2015-09-24 18:32
strange. I'll see if I can reproduce the bug

**Comment by msyadav88** [comment] 2015-09-24 18:37
Also this is working 
http://v2.iregister.ie/wp-json/ee/v4.6/registrations?access_token=myaccesstoken&filter[where][REG_ID]=94

**Comment by mnelson4** [comment] 2015-09-24 18:44
I've just been using the basic auth plugin for authentication so far and found using `{site_url}/wp-json/ee/v4.6/registrations?filter[where][REG_ID]=1` worked just fine. So it seems to be an issue relating to however you're authenticating. Are you using https://wordpress.org/plugins/oauth2-provider/ ?

> Also this is working 
> http://v2.iregister.ie/wp-json/ee/v4.6/registrations?access_token=myaccesstoken&filter[where][REG_ID]=94

It seems that if providing a querystring you need to explicitly provide the accesstoken in the querystring

**Comment by msyadav88** [comment] 2015-09-24 18:51
Hi mnelson4,

Please can you know me to get the registration id from EE_registration class
I got the reg_code by $registration->reg_code()
But there is not function such as $registration->reg_id()

**Comment by mnelson4** [comment] 2015-09-24 18:54
take a look at the class `EE_Registration` and its parent `EE_Soft_Delete_Base_Class` and `EE_Base_Class`. I think the method you want is just `ID()` on `EE_Base_Class`

**Comment by mnelson4** [comment] 2015-09-24 18:56
and regarding your original error, I'd verify you can pass querystring variables on normal WP endpoitns without authentication problems. Eg http://v2.iregister.ie/wp-json/posts?post_type=page etc because this sounds more like an authentication issue than an EE api issue

**Comment by msyadav88** [comment] 2015-09-24 19:30
Thanks Mnelson for your support

**Comment by msyadav88** [comment] 2015-09-24 19:33
Hi Mnelson,

I have one more issue. 
http://v2.iregister.ie/wp-json/ee/v4.6/registrations/94/?access_token=myaccesstoken&include=Attendee.ATT_email
This gives only attendee's ATT_ID field value and not attendee's email address.
Can you help me please.

**Comment by mnelson4** [comment] 2015-09-24 19:39
are you certain it's ONLY getting the ATT_ID field? It should return the ATT_ID (by default) and teh ATT_email.
This query http://v2.iregister.ie/wp-json/ee/v4.6/events?include=Datetime.DTT_EVT_start&filter[limit]=1 includes the related datetimes' DTT_ID and DTT_EVT_start

**Comment by msyadav88** [comment] 2015-09-24 20:00
I thinks that its the error of curl posting or wp rest api
If I direct open this url on browser
http://v2.iregister.ie/wp-json/ee/v4.6/registrations/94/?access_token=myaccesstoken&include=Attendee.ATT_email  , then it  gives both att_id and att_email 
But  if I call it through curl setup , then it only gives att_id.

**Comment by mnelson4** [comment] 2015-09-24 20:07
ah, curl mustn't be happy with the `.` in `Attendee.ATT_email`. If you send a request to http://v2.iregister.ie/wp-json/ee/v4.6/events?include=Datetime.&filter[limit]=1 it similarly only return sthe datetime's DTT_ID.
Maybe curl requires you to escape the period?

**Comment by msyadav88** [comment] 2015-09-25 10:59
Hi mnelson,

I have setup the oauth authentication from referring below link
https://www.youtube.com/watch?v=pRFCmjiRNco

I am just stuck in a issue.
Below code is working properly
    $client->setAccessToken('myaccesstoken');
    $url = 'http://v2.iregister.ie/wp-json/ee/v4.6/registrations';
    $response = $client->fetch($url);
But below code giving error
    $client->setAccessToken('myaccesstoken');
    $url = 'http://v2.iregister.ie/wp-json/ee/v4.6/registrations?';
    $response = $client->fetch($url);

Error: Sorry, you are not allowed to list registrations. Missing permissions: ee_read_registrations,ee_read_others_registrations

**Comment by mnelson4** [comment] 2015-09-25 17:00
HI @msyadav88, I thought you said you could manually add the access token to the URL string and it would work? eg `http://v2.iregister.ie/wp-json/ee/v4.6/registrations?access_token=myaccesstoken` works right? Is that an option?
Also, do the WP core endpoints have the same problem? ie, does `http://v2.iregister.ie/wp-json/users?` give you an authentication error too? If so this issue would best be brought up on the wp-oauth issue tracker: https://github.com/justingreerbbi/wordpress-oauth-server/issues

**Comment by msyadav88** [comment] 2017-01-17 18:57
Hi @mnelson4 ,
After some months I again start facing the same below on http://iregister.ie/v2/wp-json/ee/v4.8.36/registrations/21165?include=Answer.ANS_value,Answer.Question.*,Attendee.*,Event.EVT_ID&access_token=myaccesstoken

{"code":"rest_user_cannot_read","message":"Sorry, you cannot read this registration. Missing permissions are: ee_read_registrations,ee_read_others_registrations","data":{"status":403}}

It was working till now. Not know why it starts giving such error. I think as the version of ee4 is changed the endpoints are also get changed.

**Comment by mnelson4** [comment] 2017-01-17 21:05
That error means that you're not authenticated, so it's most likely an issue between the authentication plugin and WP; but it's possible EE is somehow messing that up too (less likely though).
Did you just upgrade EE? Or did you upgrade WP? If so, what did you just upgrade from?
Are you getting similar authentication problems when using the WP core endpoints?

**Comment by msyadav88** [comment] 2017-01-18 12:56
Hi @mnelson4 , 
My wordpress version is 4.6.2.  Event espresso 's version is 4.9.19
http://iregister.ie/v2/wp-json/ee/v4.8.36/events This is working
Also if wp-json or wp rest api plugins are mandatory?

**Comment by nerrad** [comment] 2017-01-18 14:36
The latest released of EE is 4.9.26.p and the latest version of WordPress is 4.7.1 - I'd recommend first trying to upgrade to those latest versions and see if you still experience the issues.  When you upgrade you won't need the WP REST api plugin installed.  I'm not sure what your experience would be on 4.6.2 of WP, you would need the WP REST api plugin installed if you want the WordPress core endpoints (/posts/ etc) but the version of the REST api plugin to install might be tricky to figure out because there were changes made to it since the core endpoints for WP were merged into core.

So the bottom line is, upgrade to latest of WP and EE before troubleshooting.

**Comment by msyadav88** [comment] 2017-01-18 18:56
Thanks for the support.
I have upgraded wordpress and EE to latest version but the same problem.
http://iregister.ie/v2/wp-json/wp/v2/users is working.

Previously EE version was 4.8.36 so its endpoint was http://iregister.ie/v2/wp-json/ee/v4.8.36/registrations/21165
Now the EE version is 4.9.26 then its endpoint should be http://iregister.ie/v2/wp-json/ee/v4.9.26/registrations/21165  ?

http://iregister.ie/v2/wp-json/ee/v4.9.26/registrations gives below error
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

**Comment by nerrad** [comment] 2017-01-18 19:09
Our endpoints do not version with each ee core release anymore.  You can read [this article](http://developer.eventespresso.com/rest-api-addition-in-event-espresso-4-8-40-new-backwards-compatibility-policy/) for more info.  Thus, the latest versioned endpoint to use is `/ee/v4.8.36`.

**Comment by joshfeck** [comment] 2017-01-18 20:00
Your server doesn't automatically allow passing the Authorization headers. So to fix this, the .htaccess file located in the /v2/ directory of your server needs an edit. 

Line 41 read like this:
`RewriteRule ^index\.php$ - [L]`

it now reads as:

`RewriteRule ^index\.php$ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]`

If the above gets changed back at any time in the future, you'll need to make that edit to the .htaccess file again.

You'll see now that the Authorization headers can get passed, the /registrations endpoint works now:

[![Screenshot 1:18:17, 2:57 PM.png](https://s30.postimg.org/q9p5ea71d/Screenshot_1_18_17_2_57_PM.png)](https://postimg.org/image/lb1mzr38d/)

**Comment by msyadav88** [comment] 2017-01-20 05:33
Thank for you support

Could you please provide me any reference link from where it could help me integrating the ee4 api through basic authentication. You tube video will also be appreciated.

**Comment by msyadav88** [comment] 2017-01-20 05:36
Also please let me know which authentication method is best for it. I guess Application password.

**Comment by nerrad** [comment] 2017-01-20 13:38
EE does nothing unique regarding authenticating with Basic Auth, there's lots of documentation that can be googled online about authenticating for things with Basic Auth.  There's also documentation that can be googled online about using the Application Passwords plugin. All the best with your project.  I'm going to close this thread now because the original request has been resolved.

**Closed as completed by nerrad** 2017-01-20 13:38 UTC
Labels: unverified bug
